---
version: 0.2
env:
  variables:
    env: ""
    account_id: ""
    service_name: ""
phases:
  pre_build:
    commands:
      - echo "install Packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - mv ./packer /usr/local/bin/. && rm -f packer.zip
      - echo "install jq"
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq && mv ./jq /usr/local/bin/.
      - echo "validate create.json"
      - packer validate .packer/create.json
  build:
    commands:
      - echo "configure AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id $(jq -r '.AccessKeyId' aws_credentials.json)
      - aws configure set aws_secret_access_key $(jq -r '.SecretAccessKey' aws_credentials.json)
      - aws configure set aws_session_token $(jq -r '.Token' aws_credentials.json)
      - commitid=$(git rev-parse --short=9 HEAD)
      
      - echo "build AMI..."
      - packer build -var commit_id=$commitid .packer/create.json
      - ami_id=$(cat manifest.json | jq -r .builds[0].artifact_id | cut -d ':' -f2)
      
      - echo "set parameter..."
      - aws ssm put-parameter --name "/$service_name/$env/ami_id" --value ${ami_id} --type "String" --overwrite
      - aws ssm put-parameter --name "/$service_name/$env/commitid" --value ${commitid} --type "String" --overwrite
  post_build:
    commands:
      - echo "Finish creating AMI. $(date)"